### ISSUE TITLE
Can't resolve dependency

### ISSUE THREAD

**Issue by nicholas-parker** [ntegral/nestjs-sendgrid#1]
Followed the instructions and added Sendgrid into the core module as below

import { Module } from '@nestjs/common';
import { SendGridModule } from '@ntegral/nestjs-sendgrid';
import { OutboundChannelsController } from './outbound-channels.controller';
import { EmailChannelProvider } from './email-channel-provider';

@Module({
  imports: [SendGridModule.forRoot({
             apiKey: '123',
             })],
  controllers: [OutboundChannelsController],
  providers: [EmailChannelProvider],
})
export class AppModule {}

The following error is reported on start up:

Error: Nest can't resolve dependencies of the SendGridService (?). Please make sure that the argument SendGridModuleOptions at index [0] is available in the SendGridCoreModule context.

**Comment by jessepinho** [comment]
Same issue here. Any suggestions @ntegral ?

**Comment by framled** [comment]
I'm making my unit test and trying to mock this module, but I got this error.

**Comment by ntegral** [comment]
I'm looking into this now... Sorry for the delay

**Comment by ntegral** [comment]
@nicholas-parker, @jessepinho @framled 

Please try the latest release of the package.  It was tested and the latest version should not have this issue.. Thx..  Let me know if it is working as expected and I'll close the issue.

**Comment by ntegral** [comment]
This issues have been resolved please install the latest version.
